### ISSUE TITLE
rfc5234 core rules

### ISSUE THREAD

**Issue by bgrayburn** [ldthomas/apg-js2#2]
I seem to be getting that ALPHA and WSP, etc. aren't defined. This are specified in the core rules section of the rfc spec. Am I missing where these are or are they not implemented in this parser? Thank you!

**Comment by ldthomas** [comment]
Appendix B of RFC5234 indicates that these are the core rules that they have used in their ABNF definition of ABNF. Outside of that I don't think they have any special meaning. I would never bring all of those unused rules into every grammar I wrote by default. But if you want them you can copy them from RFC5234 into a separate file and tack it onto your grammars by inputting multiple files. The ability to bring in predefined,  commonly used rules is the reason for allowing multiple input files.

**Comment by bgrayburn** [comment]
got it, that's what I just ended up doing. Thank you! Super useful library
