### ISSUE TITLE
Move functionality to apg-lib

### ISSUE THREAD

**Issue by fwal** [ldthomas/apg-js2#5]
Most of the functionality could be exported to `apg-js2-lib` in order to make the apg-js2 suite of packages platform agnostic and would enable packages like `apg-js2-exp` compatible with react native (ldthomas/apg-js2-exp#3) 

An alternative would be to make a `apg-js2-parse` lib or something...

What do you think?

**Comment by ldthomas** [comment]
I'm not familiar with React Native, but with a quick look I see it builds mobile apps with JavaScript and node.js. Definitely worth making **apg-exp** compatible with. I would have to break **apg** into two parts, as you suggested, to make it work – one part would essentially be an **apg** API, the other would be the command line app that reads a grammar file and outputs a parser file. I don't really like the idea of breaking it into to repos, but it's probably the only way. (Moving stuff into **apg-lib** won't work for several reasons.)

On the other hand, I've thought a number of times that an **apg** API for developers would be a good thing to do. I have already used parts of it as an ersatz API to build **apg-exp** & **apg.html**. Plus I'm working on another that may end up having to use it as well. 

But if I were to make a real API for public use, I will need to do quite a bit of rearranging internally to make it happen in a well-organized way.

What would be your reaction to an **apg** API? It would still be a node.js/npm library but without the I/O.

**Comment by ldthomas** [comment]
Try it now. I've split apg and apg-conv into two repos, one is an API with no file system dependencies and the other is an I/O shell for the desktop app. apg-exp should no longer have any "fs" dependencies. Let me know if it still doesn't work with react native.
